from __future__ import annotations

from dataclasses import dataclass

EXCLUDED_TABLES = {"GL_RPT_AccountBalance", "stk_inventory"}


BUSINESS_TABLE_ORDER: dict[str, list[str]] = {
    "saleorder": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FBILLTYPENAME",
        "FBILLNO",
        "FDATE",
        "FCUSTNAME",
        "FSALEORONAME",
        "FCUSTGROUP",
        "FMATERIALID",
        "FMATERIALNUMBER",
        "FMATERIALNAME",
        "FMATERIALTYPE",
        "FMATERIALSORT",
        "FQTY",
        "FStockOutQty",
        "FCloseStatus",
        "FMrpCloseStatus",
        "FDOCUMENTSTATUS",
        "FDeliveryDate",
        "FModifyDate",
        "FDESCRIPTION",
        "SYNC_TIME",
    ],
    "sal_outstock": [
        "FENTRYID",
        "FSEQ",
        "FBILLTYPENAME",
        "FBILLNO",
        "FDATE",
        "FCUSTNAME",
        "FSALEORGNAME",
        "FCUSTGROUP",
        "FMATERIALNUMBER",
        "FMATERIALNAME",
        "FMATERIALTYPE",
        "FMATERIALSORT",
        "FREALQTY",
        "FSRCBILLNO",
        "FMODIFYDATE",
        "FDESCRIPTION",
        "SYNC_TIME",
    ],
    "sal_returnstock": [
        "FENTRYID",
        "FBILLNO",
        "FDATE",
        "FRetcustNAME",
        "FRetcustGROUP",
        "FSalesManNAME",
        "FReturnType",
        "FMaterialFNUMBER",
        "FMaterialNAME",
        "FMaterialTYPE",
        "FMaterialSort",
        "FRealQty",
        "FDeliveryDate",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "pln_forecast": [
        "FENTRYID",
        "FBILLNO",
        "FDATE",
        "FFOREORGNAME",
        "FCUSTNAME",
        "FCUSTGROUP",
        "FMATERIALNUMBER",
        "FMATERIALNAME",
        "FORA_BASE_FNAME",
        "FORA_BASEPROPERTY_CA9",
        "FORA_BASEPROPERTY_UKY",
        "FQTY",
        "F_ORA_DATE",
        "FMODIFYDATE",
        "FDESCRIPTION",
        "SYNC_TIME",
    ],
    "sal_deliverynotice": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FBillNo",
        "FDate",
        "FCUSTNAME",
        "FMaterialNUMBER",
        "FMaterialNAME",
        "FQTY",
        "FSumOutQty",
        "FSrcBillNo",
        "FCLOSESTATUS_MX",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "prd_instock": [
        "FID",
        "FENTRYID",
        "FBILLNO",
        "FDATE",
        "FMATERIALID",
        "FREALQTY",
        "FSRCBILLNO",
        "FSrcEntrySeq",
        "FMoBillNo",
        "FMoEntrySeq",
        "FDOCUMENTSTATUS",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "prd_mo": [
        "FID",
        "FBILLNO",
        "FBILLTYPE",
        "FDATE",
        "FPRDORGID",
        "FWORKSHOPID",
        "FDOCUMENTSTATUS",
        "FCANCELSTATUS",
        "FCREATEDATE",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "prd_moentry": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FSRCBILLNO",
        "FSRCBILLENTRYID",
        "FSRCBILLENTRYSEQ",
        "FSALEORDERNO",
        "FMATERIALID",
        "FMATERIALNUMBER",
        "FDESCRIPTION",
        "FQTY",
        "FSTOCKINQUAAUXQTY",
        "FBOMID",
        "FREQUESTORGID",
        "FSTOCKINORGID",
        "FSTOCKID",
        "FWORKSHOPID",
        "FPLANSTARTDATE",
        "FPLANFINISHDATE",
        "FStatus",
        "F_ORA_TEXT1",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "customer": [
        "FCUSTID",
        "FNUMBER",
        "FNAME",
        "FGROUP",
        "FSELLERNAME",
        "FSTAFF",
        "FCUSTLEVEL",
        "FCUSTPYPE",
        "FCREATEDATE",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "prd_ppbom": [
        "FID",
        "FBILLNO",
        "FMATERIALID",
        "FPRDORGID",
        "FWORKSHOPID",
        "FBOMID",
        "FMOID",
        "FMOBILLNO",
        "FMOENTRYID",
        "FMOENTRYSEQ",
        "FMOTYPE",
        "FSALEORDERID",
        "FSALEORDERNO",
        "FSALEORDERENTRYID",
        "FSALEORDERENTRYSEQ",
        "FBASEQTY",
        "FQTY",
        "FDOCUMENTSTATUS",
        "FCREATEDATE",
        "FAPPROVEDATE",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "prd_ppbomentry": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FMOID",
        "FMOBILLNO",
        "FMOENTRYID",
        "FMOENTRYSEQ",
        "FBOMENTRYID",
        "FMATERIALID",
        "FBASESTDQTY",
        "FBASENEEDQTY",
        "FBASEMUSTQTY",
        "FSTDQTY",
        "FNEEDQTY",
        "FMUSTQTY",
        "FBASEPICKEDQTY",
        "FNEEDDATE",
        "FPLANEND",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "bd_material": [
        "FMATERIALID",
        "FNUMBER",
        "FMASTERID",
        "FNAME",
        "FSPECIFICATION",
        "FDESCRIPTION",
        "FBARCODE",
        "FMATERIALGROUP",
        "FCREATEORGID",
        "FUSEORGID",
        "FCATEGORYID",
        "FTYPEID",
        "FERPCLSID",
        "FDOCUMENTSTATUS",
        "FFORBIDSTATUS",
        "FREFSTATUS",
        "F_TMHE_TEXT",
        "F_JY_TEXT",
        "F_JY_TEXT1",
        "F_JY_TEXT2",
        "F_JYX_TEXT1",
        "F_JYX_TEXT2",
        "F_JYX_TEXT3",
        "F_JYX_TEXT4",
        "F_JYX_ASSISTANT",
        "F_JYX_ASSISTANT1",
        "F_JYX_ASSISTANT2",
        "F_JY_QTY",
        "F_JY_QTY1",
        "F_KDKF_HJFS",
        "F_ORA_TEXT_9SB",
        "F_ORA_TEXT_QTR",
        "F_ORA_TEXT_QTR1",
        "FCREATEDATE",
        "FAPPROVEDATE",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "eng_bom": [
        "FID",
        "FMASTERID",
        "FNUMBER",
        "FBILLTYPE",
        "FMATERIALID",
        "FUSEORGID",
        "FBASEUNITID",
        "FQTY",
        "FBOMUSE",
        "FDOCUMENTSTATUS",
        "FFORBIDSTATUS",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "eng_bomchild": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FMASTERID",
        "FMATERIALID",
        "FCHILDNUMBER",
        "FCHILDNAME",
        "FMATERIALTYPE",
        "FNUMERATOR",
        "FDENOMINATOR",
        "FQTY",
        "FACTUALQTY",
        "FISSUETYPE",
        "FBACKFLUSHTYPE",
        "FSUPPLYORG",
        "FSTOCKID",
        "FENTRYROWID",
        "FREPLACEGROUP",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "bd_stock": [
        "FSTOCKID",
        "FMASTERID",
        "FNUMBER",
        "FNAME",
        "FDESCRIPTION",
        "FUSEORGID",
        "FDOCUMENTSTATUS",
        "FFORBIDSTATUS",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
    "pur_purchaseorder": [
        "FID",
        "FENTRYID",
        "FBillNo",
        "FSupplier",
        "FPurchaseDept",
        "F_ora_Assistant",
        "FNUMBER",
        "FNAME",
        "FSpecification",
        "FQTY",
        "FDocumentStatus",
        "FCreateDate",
        "FApproveDate",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "sub_subreqorder": [
        "FID",
        "FENTRYID",
        "FBillTypeNAME",
        "FBillNo",
        "FDATE",
        "FSrcBillId",
        "FSRCBILLNO",
        "FSRCBILLENTRYID",
        "FSRCBILLENTRYSEQ",
        "FCustomer",
        "FSupplier",
        "FNUMBER",
        "FDescription",
        "FQty",
        "FStockInQty",
        "FDOCUMENTSTATUS",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "ap_payable": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FBILLNAME",
        "FBILLNO",
        "FDATE",
        "FPURCHASEORGNAME",
        "FCUSTOMER",
        "FSUPPLIERNAME",
        "FSETACCOUNTTYPE",
        "FMATERIALNUMBER",
        "FMATERIALNAME",
        "FPRICEUNITNAME",
        "FPRICEQTY",
        "FALLAMOUNTFOR_D",
        "FNOTAXAMOUNTFOR",
        "FDISCOUNTAMOUNTFOR",
        "FModifyDate",
        "SYNC_TIME",
    ],
    "ar_receivable": [
        "FID",
        "FENTRYID",
        "FSEQ",
        "FBILLNAME",
        "FBILLNO",
        "FDATE",
        "FCUSTOMERNAME",
        "FSETACCOUNTTYPE",
        "FBASEPROPERTY1",
        "FMATERIALNUMBER",
        "FMATERIALNAME",
        "FTAXPRICE",
        "FPRICEQTY",
        "FALLAMOUNTFOR_D",
        "FMODIFYDATE",
        "SYNC_TIME",
    ],
}


@dataclass(frozen=True)
class IndexPlan:
    name: str
    columns: tuple[str, ...]
    unique: bool = True
    clustered: bool = False


EXTRA_INDEX_PLANS: dict[str, list[IndexPlan]] = {
    "sal_outstock": [IndexPlan("UX_sal_outstock_fentryid", ("FENTRYID",), unique=True, clustered=True)],
    "pln_forecast": [IndexPlan("UX_pln_forecast_fentryid", ("FENTRYID",), unique=True, clustered=True)],
    "prd_moentry": [IndexPlan("UX_prd_moentry_fentryid", ("FENTRYID",), unique=True, clustered=True)],
    "prd_ppbomentry": [IndexPlan("UX_prd_ppbomentry_fentryid", ("FENTRYID",), unique=True, clustered=True)],
    "prd_instock": [IndexPlan("UX_prd_instock_fentryid", ("FENTRYID",), unique=True, clustered=False)],
    "sub_subreqorder": [IndexPlan("UX_sub_subreqorder_fid_fentryid", ("FID", "FENTRYID"), unique=True, clustered=True)],
    "eng_bomchild": [IndexPlan("UX_eng_bomchild_fid_fentryid", ("FID", "FENTRYID"), unique=True, clustered=False)],
    "ar_receivable": [IndexPlan("UX_AR_receivable_fentryid", ("FENTRYID",), unique=True, clustered=True)],
}


def resolve_desired_order(table_name: str, existing_columns: list[str]) -> list[str]:
    desired = BUSINESS_TABLE_ORDER.get(table_name.lower(), [])
    existing_lookup = {column.lower(): column for column in existing_columns}

    ordered: list[str] = []
    for column in desired:
        resolved = existing_lookup.get(column.lower())
        if resolved and resolved not in ordered:
            ordered.append(resolved)

    for column in existing_columns:
        if column not in ordered:
            ordered.append(column)
    return ordered
